/**
 * clangdConfig.ts
 * ───────────────
 * Bridges Arduino Grease and the clangd language server.
 *
 * What is clangd?
 *   clangd is the LLVM C++ language server. It powers all the rich editor
 *   features you expect in modern C++ code — hover docs, signature help,
 *   go-to-definition, autocomplete, rename, etc. — by actually *parsing* the
 *   translation unit, not just tokenising it.
 *
 * Why this module exists:
 *   `.ino` files are not standalone C++. Before compilation, arduino-cli
 *   preprocesses them: it inserts `#include <Arduino.h>`, generates forward
 *   declarations for any functions defined later in the file, and concatenates
 *   tab files alphabetically. Clangd has no idea about any of that — left to
 *   itself it would either refuse `.ino` files outright or fill them with red
 *   squiggles for every reference to `setup`, `loop`, `Serial`, etc.
 *
 *   This module fixes that by writing two artifacts into the sketch root:
 *     1. `compile_commands.json` — generated by `arduino-cli compile
 *        --only-compilation-database`, tells clangd the exact compiler flags
 *        and include paths for *this* board's toolchain.
 *     2. `.clangd` — a small YAML config that tells clangd to treat .ino as
 *        C++ and force-include `Arduino.h`, mirroring what the preprocessor
 *        does at real compile time.
 *
 *   With both in place, hovering over `digitalWrite` in an .ino file shows
 *   its signature and docs — the same UX you get on a .json file out of the
 *   box, just bridged through clangd.
 */

import * as vscode from "vscode";
import * as fs from "node:fs";
import * as path from "node:path";
import { generateCompileCommands } from "./arduinoCli";
import { buildClangdYaml } from "./docsPatcher";
import { findMainSketchFile, getSketchFolder, validateSketchFolder } from "./sketch";

/**
 * Write `.clangd` into the given sketch folder if it's missing or its content
 * has drifted. Idempotent: re-running on an already-correct file is a no-op.
 *
 * The YAML force-includes both `Arduino.h` (mirroring the arduino-cli
 * preprocessor) and the bundled hover-docs sidecar so hovering `pinMode`,
 * `digitalWrite`, etc. in any sketch shows the Doxygen comments.
 */
const GREASE_CLANGD_MARKER = "# Generated by Arduino Grease.";

export function writeClangdConfig(
  sketchFolder: string,
  sidecarPath: string,
  output: vscode.OutputChannel,
): boolean {
  if (!sketchFolder) return false;
  try {
    const target = path.join(sketchFolder, ".clangd");
    const desired = buildClangdYaml(sidecarPath);
    let needsWrite = true;
    try {
      const existing = fs.readFileSync(target, "utf8");
      if (existing === desired) {
        needsWrite = false;
      } else if (!existing.startsWith(GREASE_CLANGD_MARKER)) {
        // User-owned .clangd — don't clobber it.
        output.appendLine(`[clangd] Leaving user-owned ${target} untouched.`);
        return true;
      }
    } catch {
      /* file doesn't exist — needsWrite stays true */
    }
    if (needsWrite) {
      fs.writeFileSync(target, desired);
      output.appendLine(`[clangd] Wrote ${target}`);
    }
    return true;
  } catch (e) {
    output.appendLine(`[clangd] Failed to write .clangd: ${e instanceof Error ? e.message : String(e)}`);
    return false;
  }
}

/**
 * Decide if compile_commands.json is fresh enough to skip regeneration.
 * Stale = older than the main .ino file, or missing entirely.
 *
 * We use this for "first open" so we don't run an arduino-cli compile on every
 * activation if nothing has changed.
 */
export function compileCommandsIsStale(sketchFolder: string): boolean {
  const ccJson = path.join(sketchFolder, "compile_commands.json");
  if (!fs.existsSync(ccJson)) return true;
  const main = findMainSketchFile(sketchFolder);
  if (!main) return true;
  try {
    const ccStat = fs.statSync(ccJson);
    const inoStat = fs.statSync(main);
    return inoStat.mtimeMs > ccStat.mtimeMs;
  } catch {
    return true;
  }
}

/**
 * One-shot "make IntelliSense work for this sketch" call.
 *
 * Drops .clangd, then asks arduino-cli to regenerate compile_commands.json.
 * Both writes go into the sketch root because clangd searches upward from
 * the file you're editing to find them.
 *
 * Before invoking arduino-cli (which has strict rules — see
 * `validateSketchFolder`), we sanity-check the folder. The most common user
 * mistake is "loose .ino" — putting `MySketch.ino` straight inside a folder
 * named something else (e.g. `Arduino/`). arduino-cli rejects those with
 * "main file missing: Arduino.ino". We catch it here and offer an in-IDE
 * action to move the file into a properly-named subfolder.
 *
 * Returns true if compile_commands.json was generated, false otherwise.
 */
export async function refreshIntelliSense(args: {
  sketchFolder: string;
  fqbn: string | null;
  sidecarPath: string;
  output: vscode.OutputChannel;
  /** When true, suppress modal popups (useful for silent background calls like first-open). */
  silent?: boolean;
}): Promise<boolean> {
  const { sketchFolder, fqbn, sidecarPath, output, silent } = args;
  if (!sketchFolder) {
    output.appendLine("[clangd] No sketch folder — IntelliSense refresh skipped.");
    return false;
  }

  // Always write .clangd — it's cheap and idempotent, and it makes
  // hover/completion work even on individual files clangd can parse standalone.
  writeClangdConfig(sketchFolder, sidecarPath, output);

  // Sanity-check the sketch folder before invoking arduino-cli.
  const validation = validateSketchFolder(sketchFolder);
  if (validation.kind === "name-mismatch") {
    output.appendLine(
      `[clangd] Sketch validation failed: '${path.basename(validation.looseIno)}' is loose inside '${path.basename(validation.folder)}/'. Arduino requires it to live at '${validation.expectedPath}'.`,
    );
    if (!silent) {
      void offerNameMismatchFix(validation, output);
    }
    return false;
  }
  if (validation.kind === "missing-ino") {
    output.appendLine(`[clangd] Sketch validation failed: no .ino in ${validation.folder}.`);
    if (!silent) {
      vscode.window.showWarningMessage(
        `Arduino Grease: ${validation.folder} contains no .ino file. Open or create a sketch first.`,
      );
    }
    return false;
  }
  if (validation.kind === "ambiguous") {
    output.appendLine(
      `[clangd] Sketch validation failed: ${validation.candidates.length} .ino files in ${validation.folder} and none matches the folder name. Pick one and rename the folder to match.`,
    );
    if (!silent) {
      vscode.window.showWarningMessage(
        `Arduino Grease: Multiple .ino files in this folder. Move the one you're editing into its own folder (e.g., MySketch/MySketch.ino) so Arduino can compile it.`,
      );
    }
    return false;
  }

  // validation.kind === "ok"
  if (!fqbn) {
    output.appendLine(
      "[clangd] No board target set — .clangd written but compile_commands.json skipped (pick a board first).",
    );
    return false;
  }
  await generateCompileCommands(fqbn, sketchFolder, output);
  return true;
}

/**
 * Surfaced when a user has `Folder/Sketch.ino` (loose) instead of the required
 * `Folder/Sketch/Sketch.ino`. Offers an in-IDE "Auto-fix" action that creates
 * the proper subfolder, moves the file, and reopens it from the new path.
 *
 * Intentionally non-destructive: if the destination already exists, the
 * Auto-fix bails out rather than overwrite.
 */
async function offerNameMismatchFix(
  v: { folder: string; looseIno: string; expectedPath: string },
  output: vscode.OutputChannel,
): Promise<void> {
  const looseName = path.basename(v.looseIno);
  const action = await vscode.window.showWarningMessage(
    `Arduino Grease: "${looseName}" is in the wrong place.\n\n` +
      `Arduino requires sketches to live in a folder of the same name. ` +
      `Right now it's at ${v.looseIno}, but Arduino expects ${v.expectedPath}.`,
    { modal: false },
    "Auto-fix (move into subfolder)",
    "Open Docs",
  );
  if (action === "Open Docs") {
    void vscode.env.openExternal(
      vscode.Uri.parse("https://docs.arduino.cc/learn/programming/sketches/"),
    );
    return;
  }
  if (action !== "Auto-fix (move into subfolder)") return;

  const destDir = path.dirname(v.expectedPath);
  try {
    if (fs.existsSync(v.expectedPath)) {
      vscode.window.showErrorMessage(
        `Arduino Grease: Cannot auto-fix — ${v.expectedPath} already exists.`,
      );
      return;
    }
    fs.mkdirSync(destDir, { recursive: true });
    fs.renameSync(v.looseIno, v.expectedPath);
    output.appendLine(`[clangd] Auto-fix: moved ${v.looseIno} → ${v.expectedPath}`);

    // Reopen the new file so the user keeps editing the same content.
    const doc = await vscode.workspace.openTextDocument(vscode.Uri.file(v.expectedPath));
    await vscode.window.showTextDocument(doc, { preview: false });
    vscode.window.showInformationMessage(
      `Arduino Grease: Moved ${looseName} into ${path.basename(destDir)}/. Run "Regenerate IntelliSense" to finish setup.`,
    );
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    output.appendLine(`[clangd] Auto-fix failed: ${msg}`);
    vscode.window.showErrorMessage(`Arduino Grease: Auto-fix failed — ${msg}`);
  }
}

/**
 * Drop a `.clangd` next to an arbitrary `.ino` file.
 *
 * Unlike `refreshIntelliSense`, this does NOT require the parent folder to be
 * a strict Arduino sketch (named-matching folder, single .ino, etc.). It just
 * writes the YAML config alongside the file so clangd can hover the sidecar's
 * free functions and constants without `arduino-cli` involvement.
 *
 * This is what makes hover work for a loose `.ino` saved anywhere on disk.
 */
export function writeClangdForInoFile(
  inoFsPath: string,
  sidecarPath: string,
  output: vscode.OutputChannel,
): void {
  if (!inoFsPath || !inoFsPath.toLowerCase().endsWith(".ino")) return;
  const folder = path.dirname(inoFsPath);
  writeClangdConfig(folder, sidecarPath, output);
}

/**
 * "First open" entrypoint, called from extension activation.
 *
 * Walks the workspace to find the active sketch and refreshes IntelliSense if
 * the compile_commands.json on disk is missing or older than the .ino source.
 * If nothing's stale we still write .clangd (cheap, idempotent) so users who
 * never run Verify still get hover support.
 *
 * Runs in `silent: true` mode so users aren't bothered with modal popups on
 * activation if their sketch happens to be in an invalid state — the manual
 * "Regenerate IntelliSense" command surfaces the same issues with full prompts.
 */
export async function refreshIfFirstOpen(args: {
  fqbn: string | null;
  sidecarPath: string;
  output: vscode.OutputChannel;
}): Promise<void> {
  const sketchFolder = getSketchFolder();
  if (!sketchFolder) return;
  if (!compileCommandsIsStale(sketchFolder)) {
    // Already fresh — just make sure .clangd is in place.
    writeClangdConfig(sketchFolder, args.sidecarPath, args.output);
    return;
  }
  args.output.appendLine("[clangd] compile_commands.json missing/stale — regenerating...");
  await refreshIntelliSense({
    sketchFolder,
    fqbn: args.fqbn,
    sidecarPath: args.sidecarPath,
    output: args.output,
    silent: true,
  });
}
