/**
 * docsPatcher.ts
 * ──────────────
 * Hover-documentation enrichment for the Arduino built-in API.
 *
 * Two jobs:
 *   1. buildClangdYaml(sidecarPath)
 *      Returns the `.clangd` YAML body that tells clangd to parse .ino as C++
 *      and force-include both Arduino.h and our hover-doc sidecar header.
 *
 *   2. patchInstalledCores({ log, arduinoCliPath })
 *      Walks every installed Arduino core (resolved via `arduino-cli config
 *      get directories.data`, so it works on macOS / Linux / Windows and for
 *      ESP32 users who never created an Arduino sketch folder) and adds
 *      Doxygen comments to Print.h / Stream.h / HardwareSerial.h. Idempotent:
 *      a marker comment at the top of each patched file makes re-runs no-ops.
 *      Cores whose header shape we don't recognize are skipped silently.
 *
 * Free functions only — C++ classes (Serial, Stream, Print, String) can't be
 * re-declared in a sidecar, so their hover docs live in the core headers.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { spawn } from "node:child_process";

const MARKER = "// arduino-grease:hover-docs:v1";

/**
 * Build the YAML body to drop at `<sketch>/.clangd`.
 *
 * The forward slashes are normalized so the same emitted YAML works on
 * Windows — clangd accepts forward slashes in include paths.
 */
export function buildClangdYaml(sidecarPath: string): string {
  const normalised = sidecarPath.replace(/\\/g, "/");
  const addFlags = normalised
    ? `[-xc++, -include, Arduino.h, -include, "${normalised}"]`
    : `[-xc++, -include, Arduino.h]`;
  return [
    "# Generated by Arduino Grease.",
    "# Tells clangd how to parse .ino files (they are not valid C++ on their own).",
    "CompileFlags:",
    `  Add: ${addFlags}`,
    "Index:",
    "  Background: Build",
    "",
  ].join("\n");
}

export interface WriteSketchClangdResult {
  wrote: boolean;
  path?: string;
  reason?: string;
}

/**
 * Write/refresh the `.clangd` file next to a sketch. Returns `wrote: false`
 * if the file is already up-to-date so callers can avoid noisy logs.
 */
export function writeSketchClangd(sketchDir: string, sidecarPath: string): WriteSketchClangdResult {
  if (!sketchDir) return { wrote: false, reason: "no sketchDir" };
  const target = path.join(sketchDir, ".clangd");
  const desired = buildClangdYaml(sidecarPath);
  try {
    if (fs.existsSync(target)) {
      const current = fs.readFileSync(target, "utf8");
      if (current === desired) return { wrote: false, reason: "up-to-date" };
    }
    fs.writeFileSync(target, desired, "utf8");
    return { wrote: true, path: target };
  } catch (e) {
    return { wrote: false, reason: e instanceof Error ? e.message : String(e) };
  }
}

/**
 * Locate the arduino-cli data dir. Tries `arduino-cli config get
 * directories.data` first (honors the user's actual config); falls back to
 * platform defaults if the CLI isn't on PATH.
 */
export function resolveArduinoDataDir(arduinoCliPath?: string): Promise<string | null> {
  return new Promise((resolve) => {
    const cli = arduinoCliPath || "arduino-cli";
    let stdout = "";
    let proc;
    try {
      proc = spawn(cli, ["config", "get", "directories.data"], { shell: false });
    } catch {
      resolve(null);
      return;
    }
    proc.stdout.on("data", (d) => { stdout += d.toString(); });
    proc.on("error", () => resolve(null));
    proc.on("close", () => {
      const trimmed = stdout.trim();
      if (trimmed) { resolve(trimmed); return; }
      const home = process.env.HOME || process.env.USERPROFILE || "";
      if (process.platform === "darwin") {
        resolve(path.join(home, "Library", "Arduino15"));
      } else if (process.platform === "win32") {
        const local = process.env.LOCALAPPDATA || path.join(home, "AppData", "Local");
        resolve(path.join(local, "Arduino15"));
      } else {
        resolve(path.join(home, ".arduino15"));
      }
    });
  });
}

interface PatchEdit {
  find: RegExp;
  replace: string;
}

interface Patch {
  name: string;
  signature: RegExp;
  edits: PatchEdit[];
}

const PATCH_PRINT_CLASSIC: Patch = {
  name: "Print.h (classic AVR shape)",
  signature: /virtual size_t write\(uint8_t\) = 0;\s*\n\s*size_t write\(const char \*str\)/m,
  edits: [
    {
      find: /(\n)(\s*)virtual size_t write\(uint8_t\) = 0;\n/,
      replace:
        "$1$2/**\n" +
        "$2 * \\brief Send one raw byte to the stream.\n" +
        "$2 *\n" +
        "$2 * Sends the byte unchanged (no formatting) and returns the number of\n" +
        "$2 * bytes written (0 if the underlying device couldn't accept it).\n" +
        "$2 */\n" +
        "$2virtual size_t write(uint8_t) = 0;\n",
    },
    {
      find: /\n(\s*)size_t print\(const __FlashStringHelper \*\);\n/,
      replace:
        "\n$1/**\n" +
        "$1 * \\brief Write data to the stream as human-readable text.\n" +
        "$1 *\n" +
        "$1 * Numbers are converted to a decimal string by default; the second\n" +
        "$1 * argument selects a base — DEC (10), HEX (16), OCT (8), or BIN (2).\n" +
        "$1 * For floating-point values the second argument is the number of digits\n" +
        "$1 * after the decimal point (default 2). Strings, chars, and Printables\n" +
        "$1 * are written verbatim. Returns the number of bytes sent.\n" +
        "$1 */\n" +
        "$1size_t print(const __FlashStringHelper *);\n",
    },
    {
      find: /\n(\s*)size_t println\(const __FlashStringHelper \*\);\n/,
      replace:
        "\n$1/**\n" +
        "$1 * \\brief Like print(), then send \"\\r\\n\" (carriage return + line feed).\n" +
        "$1 *\n" +
        "$1 * Identical to print() but appends a newline. The no-argument form\n" +
        "$1 * sends just the newline. Returns the number of bytes sent.\n" +
        "$1 */\n" +
        "$1size_t println(const __FlashStringHelper *);\n",
    },
  ],
};

const PATCH_STREAM_GENERIC: Patch = {
  name: "Stream.h",
  signature: /virtual int available\(\) = 0;\s*\n\s*virtual int read\(\) = 0;\s*\n\s*virtual int peek\(\) = 0;/m,
  edits: [
    {
      find: /(\n)(\s*)virtual int available\(\) = 0;\n(\s*)virtual int read\(\) = 0;\n(\s*)virtual int peek\(\) = 0;/,
      replace:
        "$1$2/**\n" +
        "$2 * \\brief Number of bytes waiting in the stream's input buffer.\n" +
        "$2 *\n" +
        "$2 * Returns 0 if nothing has arrived yet. Use this to check whether read()\n" +
        "$2 * will return immediately. Example: `if (Serial.available()) ...`.\n" +
        "$2 */\n" +
        "$2virtual int available() = 0;\n" +
        "$3/**\n" +
        "$3 * \\brief Remove and return the next byte from the stream's input buffer.\n" +
        "$3 *\n" +
        "$3 * Returns -1 if no data is available.\n" +
        "$3 */\n" +
        "$3virtual int read() = 0;\n" +
        "$4/**\n" +
        "$4 * \\brief Look at the next byte without removing it from the input buffer.\n" +
        "$4 *\n" +
        "$4 * Returns -1 if no data is available.\n" +
        "$4 */\n" +
        "$4virtual int peek() = 0;",
    },
    {
      find: /\n(\s*)long parseInt\(LookaheadMode lookahead = SKIP_ALL, char ignore = NO_IGNORE_CHAR\);\n/,
      replace:
        "\n$1/**\n" +
        "$1 * \\brief Read characters from the stream and parse them as a signed long.\n" +
        "$1 *\n" +
        "$1 * Skips leading non-digit characters (configurable via `lookahead`), then\n" +
        "$1 * reads digits until the first non-digit. Returns 0 on timeout.\n" +
        "$1 */\n" +
        "$1long parseInt(LookaheadMode lookahead = SKIP_ALL, char ignore = NO_IGNORE_CHAR);\n",
    },
    {
      find: /\n(\s*)size_t readBytes\( char \*buffer, size_t length\);/,
      replace:
        "\n$1/**\n" +
        "$1 * \\brief Read up to `length` bytes into `buffer`.\n" +
        "$1 *\n" +
        "$1 * Stops when the buffer is full or the read times out. Returns the actual\n" +
        "$1 * number of bytes placed in the buffer (0 if none).\n" +
        "$1 */\n" +
        "$1size_t readBytes( char *buffer, size_t length);",
    },
  ],
};

const PATCH_HWSERIAL_AVR: Patch = {
  name: "HardwareSerial.h (AVR concrete shape)",
  signature: /void begin\(unsigned long baud\) \{ begin\(baud, SERIAL_8N1\); \}\s*\n\s*void begin\(unsigned long, uint8_t\);/m,
  edits: [
    {
      find: /(\n)(\s*)void begin\(unsigned long baud\) \{ begin\(baud, SERIAL_8N1\); \}/,
      replace:
        "$1$2/**\n" +
        "$2 * \\brief Start the UART at the given baud rate (8N1).\n" +
        "$2 *\n" +
        "$2 * Always call this from setup() before using Serial. Common rates are\n" +
        "$2 * 9600, 19200, 38400, 57600, 115200. The other side must match.\n" +
        "$2 */\n" +
        "$2void begin(unsigned long baud) { begin(baud, SERIAL_8N1); }",
    },
    {
      find: /(\n)(\s*)void end\(\);(\s*\n)/,
      replace: "$1$2/** \\brief Shut down the UART. Frees the pins for other use. */\n$2void end();$3",
    },
  ],
};

const PATCH_HWSERIAL_API: Patch = {
  name: "HardwareSerial.h (api/ pure-virtual shape)",
  signature: /virtual void begin\(unsigned long\) = 0;\s*\n\s*virtual void begin\(unsigned long baudrate, uint16_t config\) = 0;/m,
  edits: [
    {
      find: /(\n)(\s*)virtual void begin\(unsigned long\) = 0;\n(\s*)virtual void begin\(unsigned long baudrate, uint16_t config\) = 0;/,
      replace:
        "$1$2/**\n" +
        "$2 * \\brief Start the UART at the given baud rate (8N1).\n" +
        "$2 *\n" +
        "$2 * Always call this from setup() before using Serial. Common rates are\n" +
        "$2 * 9600, 19200, 38400, 57600, 115200. The other side must match.\n" +
        "$2 */\n" +
        "$2virtual void begin(unsigned long) = 0;\n" +
        "$3/** \\brief Start the UART with an explicit frame format (SERIAL_xyz). */\n" +
        "$3virtual void begin(unsigned long baudrate, uint16_t config) = 0;",
    },
    {
      find: /(\n)(\s*)virtual void end\(\) = 0;/,
      replace: "$1$2/** \\brief Shut down the UART. Frees the pins for other use. */\n$2virtual void end() = 0;",
    },
  ],
};

const PATCHES: Patch[] = [PATCH_PRINT_CLASSIC, PATCH_STREAM_GENERIC, PATCH_HWSERIAL_AVR, PATCH_HWSERIAL_API];

interface ApplyResult {
  status: "patched" | "skipped" | "error";
  reason?: string;
  edits?: number;
}

export function applyPatchToFile(filePath: string, patch: Patch): ApplyResult {
  let content: string;
  try {
    content = fs.readFileSync(filePath, "utf8");
  } catch (e) {
    return { status: "error", reason: "read: " + (e instanceof Error ? e.message : String(e)) };
  }
  if (content.indexOf(MARKER) !== -1) return { status: "skipped", reason: "already patched" };
  if (!patch.signature.test(content)) return { status: "skipped", reason: "shape mismatch" };

  let next = content;
  let appliedCount = 0;
  for (const e of patch.edits) {
    if (e.find.test(next)) {
      next = next.replace(e.find, e.replace);
      appliedCount++;
    }
  }
  if (appliedCount === 0) return { status: "skipped", reason: "no edit anchors matched" };

  // Stamp the marker just after the first '*/' that closes the file's banner
  // comment. Falls back to file head if the file has no banner.
  if (/\*\//.test(next)) {
    next = next.replace(/\*\/\n/, "*/\n" + MARKER + "\n");
  } else {
    next = MARKER + "\n" + next;
  }

  try {
    fs.writeFileSync(filePath, next, "utf8");
    return { status: "patched", edits: appliedCount };
  } catch (e) {
    return { status: "error", reason: "write: " + (e instanceof Error ? e.message : String(e)) };
  }
}

export function findCoreHeaderFiles(dataDir: string): string[] {
  // <data>/packages/<vendor>/hardware/<arch>/<ver>/cores/<core>/{Print,Stream,HardwareSerial}.h
  // plus api/ subdir variant for modern ArduinoCore-API cores.
  const found: string[] = [];
  const packagesDir = path.join(dataDir, "packages");
  let vendors: string[];
  try { vendors = fs.readdirSync(packagesDir); } catch { return found; }
  for (const vendor of vendors) {
    const hwDir = path.join(packagesDir, vendor, "hardware");
    let archs: string[];
    try { archs = fs.readdirSync(hwDir); } catch { continue; }
    for (const arch of archs) {
      const archDir = path.join(hwDir, arch);
      let vers: string[];
      try { vers = fs.readdirSync(archDir); } catch { continue; }
      for (const ver of vers) {
        const coresDir = path.join(archDir, ver, "cores");
        let cores: string[];
        try { cores = fs.readdirSync(coresDir); } catch { continue; }
        for (const core of cores) {
          const coreDir = path.join(coresDir, core);
          for (const name of ["Print.h", "Stream.h", "HardwareSerial.h"]) {
            const direct = path.join(coreDir, name);
            const api = path.join(coreDir, "api", name);
            if (fs.existsSync(direct)) found.push(direct);
            if (fs.existsSync(api)) found.push(api);
          }
        }
      }
    }
  }
  return found;
}

export interface PatchCoresOptions {
  log?: (msg: string) => void;
  arduinoCliPath?: string;
}

export interface PatchCoresResult {
  patched: number;
  skipped: number;
  errors: number;
}

export async function patchInstalledCores(opts: PatchCoresOptions = {}): Promise<PatchCoresResult> {
  const log = opts.log || (() => {});
  const dataDir = await resolveArduinoDataDir(opts.arduinoCliPath);
  if (!dataDir) {
    log("[hover-docs] Could not resolve Arduino data dir; skipping core patches.");
    return { patched: 0, skipped: 0, errors: 0 };
  }
  log("[hover-docs] Scanning cores under " + dataDir);
  const files = findCoreHeaderFiles(dataDir);
  let patched = 0, skipped = 0, errors = 0;
  for (const file of files) {
    let result: ApplyResult = { status: "skipped", reason: "no matching patch" };
    for (const patch of PATCHES) {
      const r = applyPatchToFile(file, patch);
      if (r.status === "patched") { result = r; break; }
      if (r.status === "skipped" && r.reason === "already patched") { result = r; break; }
      result = r;
    }
    if (result.status === "patched") {
      patched++;
      log("[hover-docs] Patched " + file + " (" + result.edits + " edits)");
    } else if (result.status === "error") {
      errors++;
      log("[hover-docs] Error patching " + file + ": " + result.reason);
    } else {
      skipped++;
    }
  }
  log("[hover-docs] Done. Patched " + patched + ", skipped " + skipped + ", errors " + errors + ".");
  return { patched, skipped, errors };
}

export { MARKER };
